# Generated by Django 5.2.4 on 2025-08-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatPayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mchid', models.CharField(max_length=50, verbose_name='商户号')),
                ('serial_no', models.CharField(max_length=100, verbose_name='商户API证书序列号')),
                ('private_key', models.TextField(verbose_name='商户私钥(PEM格式)')),
                ('api_v3_key', models.CharField(blank=True, max_length=100, verbose_name='API V3密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '微信支付配置',
                'verbose_name_plural': '微信支付配置',
                'db_table': 'wechat_pay_config',
                'ordering': ['-created_at'],
            },
        ),
    ]
