# Generated by Django 5.2.4 on 2025-08-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0003_delete_wechatpayconfig_alter_databackup_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'verbose_name': '微信支付配置', 'verbose_name_plural': '微信支付配置'},
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='description',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='key',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='value',
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='api_v3_key',
            field=models.CharField(blank=True, default='', help_text='微信支付API V3密钥', max_length=100, verbose_name='API V3密钥'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='mchid',
            field=models.CharField(blank=True, default='', help_text='微信支付商户号', max_length=50, verbose_name='微信支付商户号'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='private_key',
            field=models.TextField(blank=True, default='', help_text='微信支付API私钥（PEM格式）', verbose_name='API私钥'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='serial_no',
            field=models.CharField(blank=True, default='', help_text='微信支付API证书序列号', max_length=100, verbose_name='API证书序列号'),
        ),
    ]
