# Generated by Django 5.2.4 on 2025-08-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0004_alter_systemconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='app_secret',
            field=models.CharField(blank=True, default='', help_text='微信小程序AppSecret', max_length=100, verbose_name='微信小程序AppSecret'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='appid',
            field=models.CharField(blank=True, default='', help_text='微信小程序AppID', max_length=50, verbose_name='微信小程序AppID'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='serial_no',
            field=models.CharField(blank=True, default='', help_text='商户API证书序列号', max_length=100, verbose_name='商户API证书序列号'),
        ),
    ]
