# Generated by Django 5.2.4 on 2025-08-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0005_systemconfig_app_secret_systemconfig_appid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='private_key',
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='api_v2_key',
            field=models.TextField(blank=True, default='', help_text='微信支付API v2私钥', verbose_name='API v2私钥'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='cert_file',
            field=models.TextField(blank=True, default='', help_text='微信支付证书文件内容（PEM格式）', verbose_name='微信支付证书文件'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='key_file',
            field=models.TextField(blank=True, default='', help_text='微信支付私钥文件内容（PEM格式）', verbose_name='微信支付私钥文件'),
        ),
    ]
