# Generated by Django 5.2.4 on 2025-09-09 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=64, verbose_name='OpenID')),
                ('wx_session_key', models.CharField(max_length=128, verbose_name='微信session_key')),
                ('session_cookie', models.CharField(db_index=True, max_length=64, verbose_name='会话Cookie值')),
                ('cookie_expires_at', models.DateTimeField(verbose_name='Cookie过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wx_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '微信会话(Cookie)',
                'verbose_name_plural': '微信会话(Cookie)',
                'db_table': 'wechat_session_cookie',
                'indexes': [models.Index(fields=['openid', 'session_cookie'], name='wechat_sess_openid_ef80d2_idx')],
            },
        ),
    ]
