# Generated by Django 5.2.4 on 2025-08-08 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, verbose_name='微信OpenID')),
                ('session_key', models.CharField(max_length=100, verbose_name='会话密钥')),
                ('unionid', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信UnionID')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '微信会话',
                'verbose_name_plural': '微信会话',
                'db_table': 'wechat_session',
            },
        ),
        migrations.CreateModel(
            name='WechatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, unique=True, verbose_name='微信OpenID')),
                ('unionid', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信UnionID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='会话密钥')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信昵称')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='微信头像')),
                ('gender', models.IntegerField(default=0, verbose_name='性别')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='国家')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='城市')),
                ('language', models.CharField(blank=True, max_length=20, null=True, verbose_name='语言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wechat_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '微信用户',
                'verbose_name_plural': '微信用户',
                'db_table': 'wechat_user',
            },
        ),
    ]
