# Generated by Django 5.2.4 on 2025-08-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '订单编号序列',
                'verbose_name_plural': '订单编号序列',
                'db_table': 'order_number_sequence',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='internal_order_number',
            field=models.CharField(db_index=True, default=0, max_length=12, unique=True, verbose_name='内部订单号'),
            preserve_default=False,
        ),
    ]
