# Generated by Django 5.2.4 on 2025-09-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_ordernumbersequence_order_internal_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='快递公司'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='物流单号'),
        ),
    ]
