# Generated by Django 5.2.4 on 2025-09-14 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_order_courier_company_order_tracking_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_company', models.CharField(max_length=50, verbose_name='快递公司')),
                ('tracking_number', models.CharField(max_length=100, unique=True, verbose_name='物流单号')),
                ('status', models.CharField(choices=[('pending', '待发货'), ('shipped', '已发货'), ('in_transit', '运输中'), ('out_for_delivery', '派送中'), ('delivered', '已送达'), ('failed', '派送失败'), ('returned', '已退回')], default='pending', max_length=20, verbose_name='物流状态')),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='发件人姓名')),
                ('sender_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='发件人电话')),
                ('sender_address', models.TextField(blank=True, null=True, verbose_name='发件地址')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='预计送达时间')),
                ('actual_delivery', models.DateTimeField(blank=True, null=True, verbose_name='实际送达时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='物流备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='order_management.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '物流信息',
                'verbose_name_plural': '物流信息',
                'db_table': 'logistics_info',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=20, verbose_name='新状态')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='当前位置')),
                ('description', models.TextField(blank=True, null=True, verbose_name='状态描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('logistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='order_management.logisticsinfo', verbose_name='物流信息')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '物流状态日志',
                'verbose_name_plural': '物流状态日志',
                'db_table': 'logistics_status_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
